<?php

include_once('Config.php');
include_once('BanksMap.php');
include_once('Bin.php');
include_once('CancelRefund.php');
include_once('GetInstallmentPlanForMerchant.php');
include_once('GetInstallmentPlanForUser.php');
include_once('Sale3d.php');
include_once('Sale.php');
include_once('SaleWithSavedCard.php');
include_once('SaleWithToken.php');
include_once('SaveCard.php');
include_once('TransactionQuery.php');
include_once('DeleteCard.php');
include_once('UpdateInstallmentPlan.php');

include_once('paramBasics/BIN_SanalPos.php');
include_once('paramBasics/KS_Kart_Ekle.php');
include_once('paramBasics/KS_Tahsilat.php');
include_once('paramBasics/SHA2B64.php');
include_once('paramBasics/TP_Islem_Iptal_Iade_Kismi.php');
include_once('paramBasics/TP_Islem_Odeme.php');
include_once('paramBasics/TP_Islem_Odeme_WKS.php');
include_once('paramBasics/TP_Islem_Odeme_WNS.php');
include_once('paramBasics/TP_Islem_Sorgulama.php');
include_once('paramBasics/TP_Ozel_Oran_Liste.php');
include_once('paramBasics/TP_Ozel_Oran_SK_Liste.php');
include_once('paramBasics/TP_Ozel_Oran_SK_Guncelle.php');
include_once('paramBasics/KK_Kart_Sil.php');
include_once('paramBasics/G.php');
